version = 0.1

[default.deploy.parameters]
stack_name = "order-dev"
resolve_s3 = true
s3_prefix = "order-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Stage=\"prod\""

[default.global.parameters]
region = "mx-central-1"
