version = 0.1

[default.global.parameters]
region = "mx-central-1"

[dev.deploy.parameters]
stack_name = "orderapi-dev"
resolve_s3 = true
s3_prefix = "orderapi-dev"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Stage=dev IncludeDevHost=true FrontendBaseUrl=https://hercis-orderui-dev.s3.mx-central-1.amazonaws.com FrontendCallbackPath=/index.html FrontendLogoutPath=/index.html LocalhostBaseUrl=http://localhost:5173 LocalhostCallbackPath=/ LocalhostLogoutPath=/"

override_lambda_rollback = true

[prd.deploy.parameters]
stack_name = "orderapi-prd"
resolve_s3 = true
s3_prefix = "orderapi-prd"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Stage=prd FrontendBaseUrl=https://hercis-orderui-prd.s3.mx-central-1.amazonaws.com FrontendCallbackPath=/index.html FrontendLogoutPath=/index.html"

override_lambda_rollback = true
